version: '3'
services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
    networks:
      - app_network
    container_name: django_app

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forecast
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    container_name: db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
